### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by wmcginty** [BottleRocketStudios/iOS-Scotty#16]
There are some API changes in this release (the removal of Options, so it will need to be replaced with [AnyHashable: Any]. Technically that would mean we should move to 2.0. What do you all think @tylermilner @earlgaspard .

Once we settle on a version number I'll begin the release process.

Release Checklist
- [x] Create release branch
- [x] Update version number for all targets
- [x] Update version number in Podspec
- [x] Validate README.md is still current
- [x] Create pull request into master
- [x] Create version number tag in Git
- [x] Publish release on GitHub
- [x] Publish release on Cocoapods trunk

**Comment by earlgaspard** [comment]
If the changes made results in the end user's code breaking then I am in favor of 2.0

**Comment by wmcginty** [comment]
Going to go with 2.0 then. Will attempt to get this out by EOW.
